module.exports = {
  YELP_API_KEY: '-DfYQp9sx_MBTOCvJBycr3relaYYUOmo7YWsU9DIekYPuqQS-D1yCc7_Yio0g0Ys0tNSkAqFMRlY28CrzkZbM_oercMiPS4ZcnOX4OigRsYPOoxvLOb7Xe8w3RtgWnYx',
  EVENT_BRITE_API_KEY: 'VZJDVIABPF5E75WV5L'
}